# revenue generated by each doctor
select d.doctor_name ,sum(t.treatment_cost) as Total_Revenue 
from doctors d
join appointments a 
	on d.doctor_id = a.doctor_id
join treatments t
on a.appointment_id = t.appointment_id
where a.status = "completed"
group by doctor_name;
# -----------------------------------------------------------------------------------

# average rating per doctor
select avg(r.rating) as average_rating_per_doctor 
from reviews r 
join appointments a 
	on r.appointment_id = a.appointment_id
join doctors d
	on a.doctor_id = d.doctor_id
where a.status = "completed";
# ------------------------------------------------------------------------------------

# doctors within each hospital
select h.hospital_name, d.doctor_name, sum(t.treatment_cost) as revenue,
rank() over(partition by h.hospital_id order by sum(t.treatment_cost) desc) as rank_in_hospital
from hospitals h
join doctors d
on h.hospital_id= d.hospital_id
join appointments a
on a.doctor_id = d.doctor_id
join treatments t
on a.appointment_id = t.appointment_id
where a.status = "completed"
group by h.hospital_id, h.hospital_name , d.doctor_name;
